require 'clientele/http/verb'

require 'clientele/http/verbs/connect'
require 'clientele/http/verbs/delete'
require 'clientele/http/verbs/get'
require 'clientele/http/verbs/head'
require 'clientele/http/verbs/options'
require 'clientele/http/verbs/patch'
require 'clientele/http/verbs/post'
require 'clientele/http/verbs/put'
